### ISSUE TITLE
Unable to Create Conda Environment

### ISSUE THREAD

**Issue by christos-efthymiou** [bioexcel/biobb_wf_virtual-screening#1]
I wanted to follow along with one of the tutorials, but after cloning and repository and going into the biobb_wf_virtual-screening folder, I see the following after trying to create the conda environment: 
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides ambertools >=22.0 needed by biobb_chemistry-4.1.0-pyhdfd78af_0
  - nothing provides fpocket >=3.1.4.2 needed by biobb_vs-4.1.1-pyhdfd78af_0

Could not solve for environment specs
The following packages are incompatible
├─ biobb_chemistry 4.1.0  is not installable because it requires
│  └─ ambertools >=22.0 , which does not exist (perhaps a missing channel);
└─ biobb_vs 4.1.1  is not installable because it requires
   └─ fpocket >=3.1.4.2 , which does not exist (perhaps a missing channel).

I just completed the 2 first steps of the conda installation process and then encountered the above error when I tried the third step. 

I was expecting the conda environment to be created so then I could activate it and follow along with one of the tutorials. 

 - OS: Windows 11
 - Python version: 3.10
 - BioBB version ??

**Comment by gbayarri** [comment]
Hi, both of these packages, fpocket and ambertools, are not compatible with windows. So, as the two of them are dependencies of biobb_vs and biobb_chemistry, you get this error. 

Try in ubuntu or mac. If you don't have none of these operating systems, then enable the WSL in your Windows:

https://mmb.irbbarcelona.org/biobb/availability/tutorials/windows

Best.
